### ISSUE TITLE
get_wallet_trans_history : NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by RomainFranklin** [itkin/lemonway#3]
Bonjour, je rencontre une erreur avec la method get_wallet_trans_history :

```
client = Lemonway::Client.new(
  wsdl:  "https://ws.lemonway.fr/[...]/service.asmx?wsdl",
  wl_login: "login",
  wl_pass: "pwd",
  language: "fr",
  version: "2.0",
  wallet_ip: "127.0.0.1",
)

client.get_wallet_trans_history(
  wallet:      'mon-wallet',
  start_date:  1.year.ago.to_i,
  end_date:    Time.now.to_i
)
```

erreur :

```
NoMethodError: undefined method `[]' for nil:NilClass
    from /home/[...]/gems/lemonway-1.0.0/lib/lemonway/client.rb:47:in `client_call'
    from /home/[...]/gems/lemonway-1.0.0/lib/lemonway/client.rb:29:in `method_missing'
    [...]
```

J'ai également essayé sans les élements start_date et end_date, même erreur.

Ah oui, et lorsque je ne renseigne pas le wallet, j'obtiens l'erreur: 234 : Erreur de format, je ne sais pas si c'est volontaire, mais ce n'est pas forcément précis.

Merci.

**Comment by duongphuhiep** [comment]
@itkin 

S'il y a des update, peut tu faire sur https://github.com/lemonwaysas/ruby-client-directkit-string,
stp merci

**Comment by itkin** [comment]
il y avait une typo sur le client j'ai upgradé la gem, je pense que cela clos cette issue

@RomainFranklin peux tu test en indiquant ce repo dans ton gemfile ?

**Comment by RomainFranklin** [comment]
@itkin ça fonctionne bien merci :+1:
